/*
 * This file is generated by jOOQ.
 */
package com.hedera.hashgraph.stablecoin.app.db.tables;


import com.hedera.hashgraph.stablecoin.app.db.Keys;
import com.hedera.hashgraph.stablecoin.app.db.Public;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransactionUnsetKycPassed extends TableImpl<Record> {

    private static final long serialVersionUID = -1187835364;

    /**
     * The reference instance of <code>public.transaction_unset_kyc_passed</code>
     */
    public static final TransactionUnsetKycPassed TRANSACTION_UNSET_KYC_PASSED = new TransactionUnsetKycPassed();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.transaction_unset_kyc_passed.timestamp</code>.
     */
    public final TableField<Record, Long> TIMESTAMP = createField(DSL.name("timestamp"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.transaction_unset_kyc_passed.address</code>.
     */
    public final TableField<Record, byte[]> ADDRESS = createField(DSL.name("address"), org.jooq.impl.SQLDataType.BLOB.nullable(false), this, "");

    /**
     * Create a <code>public.transaction_unset_kyc_passed</code> table reference
     */
    public TransactionUnsetKycPassed() {
        this(DSL.name("transaction_unset_kyc_passed"), null);
    }

    /**
     * Create an aliased <code>public.transaction_unset_kyc_passed</code> table reference
     */
    public TransactionUnsetKycPassed(String alias) {
        this(DSL.name(alias), TRANSACTION_UNSET_KYC_PASSED);
    }

    /**
     * Create an aliased <code>public.transaction_unset_kyc_passed</code> table reference
     */
    public TransactionUnsetKycPassed(Name alias) {
        this(alias, TRANSACTION_UNSET_KYC_PASSED);
    }

    private TransactionUnsetKycPassed(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private TransactionUnsetKycPassed(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> TransactionUnsetKycPassed(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, TRANSACTION_UNSET_KYC_PASSED);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.TRANSACTION_UNSET_KYC_PASSED_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.TRANSACTION_UNSET_KYC_PASSED_PKEY);
    }

    @Override
    public TransactionUnsetKycPassed as(String alias) {
        return new TransactionUnsetKycPassed(DSL.name(alias), this);
    }

    @Override
    public TransactionUnsetKycPassed as(Name alias) {
        return new TransactionUnsetKycPassed(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TransactionUnsetKycPassed rename(String name) {
        return new TransactionUnsetKycPassed(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TransactionUnsetKycPassed rename(Name name) {
        return new TransactionUnsetKycPassed(name, null);
    }
}
