/*
 * This file is generated by jOOQ.
 */
package com.hedera.hashgraph.stablecoin.app.db.tables;


import com.hedera.hashgraph.stablecoin.app.db.Keys;
import com.hedera.hashgraph.stablecoin.app.db.Public;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransactionFreeze extends TableImpl<Record> {

    private static final long serialVersionUID = 382782780;

    /**
     * The reference instance of <code>public.transaction_freeze</code>
     */
    public static final TransactionFreeze TRANSACTION_FREEZE = new TransactionFreeze();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.transaction_freeze.timestamp</code>.
     */
    public final TableField<Record, Long> TIMESTAMP = createField(DSL.name("timestamp"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.transaction_freeze.address</code>.
     */
    public final TableField<Record, byte[]> ADDRESS = createField(DSL.name("address"), org.jooq.impl.SQLDataType.BLOB.nullable(false), this, "");

    /**
     * Create a <code>public.transaction_freeze</code> table reference
     */
    public TransactionFreeze() {
        this(DSL.name("transaction_freeze"), null);
    }

    /**
     * Create an aliased <code>public.transaction_freeze</code> table reference
     */
    public TransactionFreeze(String alias) {
        this(DSL.name(alias), TRANSACTION_FREEZE);
    }

    /**
     * Create an aliased <code>public.transaction_freeze</code> table reference
     */
    public TransactionFreeze(Name alias) {
        this(alias, TRANSACTION_FREEZE);
    }

    private TransactionFreeze(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private TransactionFreeze(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> TransactionFreeze(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, TRANSACTION_FREEZE);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.TRANSACTION_FREEZE_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.TRANSACTION_FREEZE_PKEY);
    }

    @Override
    public TransactionFreeze as(String alias) {
        return new TransactionFreeze(DSL.name(alias), this);
    }

    @Override
    public TransactionFreeze as(Name alias) {
        return new TransactionFreeze(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TransactionFreeze rename(String name) {
        return new TransactionFreeze(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TransactionFreeze rename(Name name) {
        return new TransactionFreeze(name, null);
    }
}
