/*
 * This file is generated by jOOQ.
 */
package com.hedera.hashgraph.stablecoin.app.db.tables;


import com.hedera.hashgraph.stablecoin.app.db.Keys;
import com.hedera.hashgraph.stablecoin.app.db.Public;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransactionChangeEnforcementManager extends TableImpl<Record> {

    private static final long serialVersionUID = 1636873890;

    /**
     * The reference instance of <code>public.transaction_change_enforcement_manager</code>
     */
    public static final TransactionChangeEnforcementManager TRANSACTION_CHANGE_ENFORCEMENT_MANAGER = new TransactionChangeEnforcementManager();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.transaction_change_enforcement_manager.timestamp</code>.
     */
    public final TableField<Record, Long> TIMESTAMP = createField(DSL.name("timestamp"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.transaction_change_enforcement_manager.address</code>.
     */
    public final TableField<Record, byte[]> ADDRESS = createField(DSL.name("address"), org.jooq.impl.SQLDataType.BLOB.nullable(false), this, "");

    /**
     * Create a <code>public.transaction_change_enforcement_manager</code> table reference
     */
    public TransactionChangeEnforcementManager() {
        this(DSL.name("transaction_change_enforcement_manager"), null);
    }

    /**
     * Create an aliased <code>public.transaction_change_enforcement_manager</code> table reference
     */
    public TransactionChangeEnforcementManager(String alias) {
        this(DSL.name(alias), TRANSACTION_CHANGE_ENFORCEMENT_MANAGER);
    }

    /**
     * Create an aliased <code>public.transaction_change_enforcement_manager</code> table reference
     */
    public TransactionChangeEnforcementManager(Name alias) {
        this(alias, TRANSACTION_CHANGE_ENFORCEMENT_MANAGER);
    }

    private TransactionChangeEnforcementManager(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private TransactionChangeEnforcementManager(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> TransactionChangeEnforcementManager(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, TRANSACTION_CHANGE_ENFORCEMENT_MANAGER);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.TRANSACTION_CHANGE_ENFORCEMENT_MANAGER_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.TRANSACTION_CHANGE_ENFORCEMENT_MANAGER_PKEY);
    }

    @Override
    public TransactionChangeEnforcementManager as(String alias) {
        return new TransactionChangeEnforcementManager(DSL.name(alias), this);
    }

    @Override
    public TransactionChangeEnforcementManager as(Name alias) {
        return new TransactionChangeEnforcementManager(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TransactionChangeEnforcementManager rename(String name) {
        return new TransactionChangeEnforcementManager(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TransactionChangeEnforcementManager rename(Name name) {
        return new TransactionChangeEnforcementManager(name, null);
    }
}
