/*
 * This file is generated by jOOQ.
 */
package com.hedera.hashgraph.stablecoin.app.db.tables;


import com.hedera.hashgraph.stablecoin.app.db.Keys;
import com.hedera.hashgraph.stablecoin.app.db.Public;

import java.math.BigInteger;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransactionExternalTransfer extends TableImpl<Record> {

    private static final long serialVersionUID = -1482888420;

    /**
     * The reference instance of <code>public.transaction_external_transfer</code>
     */
    public static final TransactionExternalTransfer TRANSACTION_EXTERNAL_TRANSFER = new TransactionExternalTransfer();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.transaction_external_transfer.timestamp</code>.
     */
    public final TableField<Record, Long> TIMESTAMP = createField(DSL.name("timestamp"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.transaction_external_transfer.address_from</code>.
     */
    public final TableField<Record, byte[]> ADDRESS_FROM = createField(DSL.name("address_from"), org.jooq.impl.SQLDataType.BLOB.nullable(false), this, "");

    /**
     * The column <code>public.transaction_external_transfer.network_uri</code>.
     */
    public final TableField<Record, String> NETWORK_URI = createField(DSL.name("network_uri"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.transaction_external_transfer.address_to</code>.
     */
    public final TableField<Record, byte[]> ADDRESS_TO = createField(DSL.name("address_to"), org.jooq.impl.SQLDataType.BLOB.nullable(false), this, "");

    /**
     * The column <code>public.transaction_external_transfer.amount</code>.
     */
    public final TableField<Record, BigInteger> AMOUNT = createField(DSL.name("amount"), org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(78).nullable(false), this, "");

    /**
     * Create a <code>public.transaction_external_transfer</code> table reference
     */
    public TransactionExternalTransfer() {
        this(DSL.name("transaction_external_transfer"), null);
    }

    /**
     * Create an aliased <code>public.transaction_external_transfer</code> table reference
     */
    public TransactionExternalTransfer(String alias) {
        this(DSL.name(alias), TRANSACTION_EXTERNAL_TRANSFER);
    }

    /**
     * Create an aliased <code>public.transaction_external_transfer</code> table reference
     */
    public TransactionExternalTransfer(Name alias) {
        this(alias, TRANSACTION_EXTERNAL_TRANSFER);
    }

    private TransactionExternalTransfer(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private TransactionExternalTransfer(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> TransactionExternalTransfer(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, TRANSACTION_EXTERNAL_TRANSFER);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.TRANSACTION_EXTERNAL_TRANSFER_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.TRANSACTION_EXTERNAL_TRANSFER_PKEY);
    }

    @Override
    public TransactionExternalTransfer as(String alias) {
        return new TransactionExternalTransfer(DSL.name(alias), this);
    }

    @Override
    public TransactionExternalTransfer as(Name alias) {
        return new TransactionExternalTransfer(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TransactionExternalTransfer rename(String name) {
        return new TransactionExternalTransfer(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TransactionExternalTransfer rename(Name name) {
        return new TransactionExternalTransfer(name, null);
    }
}
