/*
 * This file is generated by jOOQ.
 */
package com.hedera.hashgraph.stablecoin.app.db.tables;


import com.hedera.hashgraph.stablecoin.app.db.Keys;
import com.hedera.hashgraph.stablecoin.app.db.Public;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransactionUnfreeze extends TableImpl<Record> {

    private static final long serialVersionUID = 344105408;

    /**
     * The reference instance of <code>public.transaction_unfreeze</code>
     */
    public static final TransactionUnfreeze TRANSACTION_UNFREEZE = new TransactionUnfreeze();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.transaction_unfreeze.timestamp</code>.
     */
    public final TableField<Record, Long> TIMESTAMP = createField(DSL.name("timestamp"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.transaction_unfreeze.address</code>.
     */
    public final TableField<Record, byte[]> ADDRESS = createField(DSL.name("address"), org.jooq.impl.SQLDataType.BLOB.nullable(false), this, "");

    /**
     * Create a <code>public.transaction_unfreeze</code> table reference
     */
    public TransactionUnfreeze() {
        this(DSL.name("transaction_unfreeze"), null);
    }

    /**
     * Create an aliased <code>public.transaction_unfreeze</code> table reference
     */
    public TransactionUnfreeze(String alias) {
        this(DSL.name(alias), TRANSACTION_UNFREEZE);
    }

    /**
     * Create an aliased <code>public.transaction_unfreeze</code> table reference
     */
    public TransactionUnfreeze(Name alias) {
        this(alias, TRANSACTION_UNFREEZE);
    }

    private TransactionUnfreeze(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private TransactionUnfreeze(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> TransactionUnfreeze(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, TRANSACTION_UNFREEZE);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.TRANSACTION_UNFREEZE_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.TRANSACTION_UNFREEZE_PKEY);
    }

    @Override
    public TransactionUnfreeze as(String alias) {
        return new TransactionUnfreeze(DSL.name(alias), this);
    }

    @Override
    public TransactionUnfreeze as(Name alias) {
        return new TransactionUnfreeze(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TransactionUnfreeze rename(String name) {
        return new TransactionUnfreeze(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TransactionUnfreeze rename(Name name) {
        return new TransactionUnfreeze(name, null);
    }
}
