/*
 * This file is generated by jOOQ.
 */
package com.hedera.hashgraph.stablecoin.app.db;


import com.hedera.hashgraph.stablecoin.app.db.tables.FlywaySchemaHistory;
import com.hedera.hashgraph.stablecoin.app.db.tables.Transaction;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Indexes0.FLYWAY_SCHEMA_HISTORY_S_IDX;
    public static final Index TRANSACTION_CALLER_VALID_START_IDX = Indexes0.TRANSACTION_CALLER_VALID_START_IDX;
    public static final Index TRANSACTION_KIND_IDX = Indexes0.TRANSACTION_KIND_IDX;
    public static final Index TRANSACTION_STATUS_IDX = Indexes0.TRANSACTION_STATUS_IDX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex("flyway_schema_history_s_idx", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
        public static Index TRANSACTION_CALLER_VALID_START_IDX = Internal.createIndex("transaction_caller_valid_start_idx", Transaction.TRANSACTION, new OrderField[] { Transaction.TRANSACTION.CALLER, Transaction.TRANSACTION.VALID_START }, false);
        public static Index TRANSACTION_KIND_IDX = Internal.createIndex("transaction_kind_idx", Transaction.TRANSACTION, new OrderField[] { Transaction.TRANSACTION.KIND }, false);
        public static Index TRANSACTION_STATUS_IDX = Internal.createIndex("transaction_status_idx", Transaction.TRANSACTION, new OrderField[] { Transaction.TRANSACTION.STATUS }, false);
    }
}
