package com.hedera.hashgraph.stablecoin;

public enum Status {
    OK,

    /**
     * Owner of the token is the zero address.
     * This status code will be raised for transactions that are non-construct
     * before the construct transaction.
     */
    OWNER_ZERO,

    CONSTRUCTOR_ASSET_PROTECTION_MANAGER_ZERO,

    /**
     * Caller of a transaction is the zero address.
     */
    CONSTRUCTOR_CALLER_ZERO,
    CONSTRUCTOR_OWNER_ALREADY_SET,
    CONSTRUCTOR_SUPPLY_MANAGER_ZERO,
    CONSTRUCTOR_TOKEN_DECIMAL_LESS_THAN_ZERO,
    CONSTRUCTOR_TOTAL_SUPPLY_LESS_THAN_ZERO,

    APPROVE_OWNER_NOT_SET,
    APPROVE_VALUE_LESS_THAN_ZERO,
    APPROVE_CALLER_TRANSFER_NOT_ALLOWED,
    APPROVE_SPENDER_TRANSFER_NOT_ALLOWED,

    MINT_OWNER_NOT_SET,
    MINT_NOT_AUTHORIZED,
    MINT_VALUE_LESS_THAN_ZERO,
    MINT_INSUFFICENT_TOTAL_SUPPLY,

    BURN_OWNER_NOT_SET,
    BURN_NOT_AUTHORIZED,
    BURN_VALUE_LESS_THAN_ZERO,
    BURN_INSUFFICENT_SUPPLY_MANAGER_BALANCE,
    BURN_INSUFFICENT_TOTAL_SUPPLY,

    TRANSFER_OWNER_NOT_SET,
    TRANSFER_VALUE_LESS_THAN_ZERO,
    TRANSFER_INSUFFICIENT_BALANCE,
    TRANSFER_NOT_ALLOWED,
    TRANSFER_CALLER_TRANSFER_NOT_ALLOWED,
    TRANSFER_TO_ADDRESS_TRANSFER_NOT_ALLOWED,

    TRANSFER_FROM_OWNER_NOT_SET,
    TRANSFER_FROM_VALUE_LESS_THAN_ZERO,
    TRANSFER_FROM_INSUFFICIENT_BALANCE,
    TRANSFER_FROM_INSUFFICIENT_ALLOWANCE,
    TRANSFER_FROM_CALLER_TRANSFER_NOT_ALLOWED,
    TRANSFER_FROM_FROM_ADDRESS_TRANSFER_NOT_ALLOWED,
    TRANSFER_FROM_TO_ADDRESS_TRANSFER_NOT_ALLOWED,

    PROPOSE_OWNER_OWNER_NOT_SET,
    PROPOSE_OWNER_CALLER_NOT_OWNER,
    PROPOSE_OWNER_ADDRESS_NOT_SET,
    PROPOSE_OWNER_TRANSFER_NOT_ALLOWED,

    CLAIM_OWNERSHIP_OWNER_NOT_SET,
    CLAIM_OWNERSHIP_CALLER_NOT_PROPOSED_OWNER,
    CLAIM_OWNERSHIP_TRANSFER_NOT_ALLOWED,

    CHANGE_SUPPLY_MANAGER_OWNER_NOT_SET,
    CHANGE_SUPPLY_MANAGER_CALLER_NOT_OWNER,
    CHANGE_SUPPLY_MANAGER_ADDRESS_NOT_SET,
    CHANGE_SUPPLY_MANAGER_TRANSFER_NOT_ALLOWED,

    CHANGE_ASSET_PROTECTION_MANAGER_OWNER_NOT_SET,
    CHANGE_ASSET_PROTECTION_MANAGER_CALLER_NOT_OWNER,
    CHANGE_ASSET_PROTECTION_MANAGER_ADDRESS_NOT_SET,
    CHANGE_ASSET_PROTECTION_MANAGER_TRANSFER_NOT_ALLOWED,

    FREEZE_OWNER_NOT_SET,
    FREEZE_NOT_AUTHORIZED,
    FREEZE_ADDRESS_IS_PRIVILEGED,

    UNFREEZE_OWNER_NOT_SET,
    UNFREEZE_NOT_AUTHORIZED,

    WIPE_OWNER_NOT_SET,
    WIPE_NOT_AUTHORIZED,
    WIPE_ADDRESS_NOT_FROZEN,

    SET_KYC_PASSED_OWNER_NOT_SET,
    SET_KYC_PASSED_NOT_AUTHORIZED,

    UNSET_KYC_PASSED_OWNER_NOT_SET,
    UNSET_KYC_PASSED_NOT_AUTHORIZED,
    UNSET_KYC_PASSED_ADDRESS_IS_PRIVILEGED,

    INCREASE_ALLOWANCE_OWNER_NOT_SET,
    INCREASE_ALLOWANCE_VALUE_IS_ZERO,
    INCREASE_ALLOWANCE_CALLER_TRANSFER_NOT_ALLOWED,
    INCREASE_ALLOWANCE_SPENDER_TRANSFER_NOT_ALLOWED,

    DECREASE_ALLOWANCE_OWNER_NOT_SET,
    DECREASE_ALLOWANCE_VALUE_IS_ZERO,
    DECREASE_ALLOWANCE_CALLER_TRANSFER_NOT_ALLOWED,
    DECREASE_ALLOWANCE_SPENDER_TRANSFER_NOT_ALLOWED,
    DECREASE_ALLOWANCE_VALUE_EXCEEDS_ALLOWANCE
}
